### ISSUE TITLE
Modulate Parameters grey ring color is too dark in Dark Mode

### ISSUE THREAD

**Issue by thadguidry** [Jojosito/MUS-X#15]
The grey modulate ring color is too dark (#202020) compared to the background color (which seems to be something close to #1A191A but not 100% sure).  I tried inspecting the code and also looking at VCV Rack Plugin API and guides, but couldn't find out where this might be modified slightly - and thus submit a PR to fix this for the Dark Mode operation.  In Regular or Light Mode, the darker black rings against the white background show up just fine and no need to modify.  Only Dark Mode really has the contrast problem with the default dark grey modulate rings around ParamWidgets.

See my proposed mockup edit using Paint program.  The below mockup view fixes with color value of (#303030) for the ENV 1 row, compared to the lower snippet where the original color value of (#202020) for modulate rings is used everywhere.  The lighter grey rings in dark mode, demonstrate a more clear view of which parameters can be modulated:

![image](https://github.com/user-attachments/assets/641da295-8dcb-420a-8896-f61d07cf978f)

Note 1:  I am also using HDR Monitors with HDR enabled on both through Windows 11 Pro.  (but the contrast problem is still significant even with HDR OFF and should be fixed regardless).

Note 2: Maybe the modulate ring default coloring is something that is a default within Rack2 in Dark Mode and should be fixed in upstream somehow, if MUS-X Synth is not changing their default color - or should override it somehow?  Dunno.

**Comment by Jojosito** [comment]
Thanks a lot for your input. I will change the rings color to #303030.
